### ISSUE TITLE
İlçenin mahalleleri string[] dönmüyor.

### ISSUE THREAD

**Issue by alpzaf** [muratgozel/turkey-neighbourhoods#8]
getCityDistrictNeighbourhoods methodunun 2.ci parametresi düzgün çalışmıyor. Tüm ilçelerin mahallelerini dönüyor.

test('validate return typeof function', () => {
    const result = getCityDistrictNeighbourhoods('34', "Sarıyer")
    expect(Array.isArray(result)).toBe(true)
})

böyle bir test yazıp pr açıcaktım ama pr kapalı

**Comment by muratgozel** [comment]
merhaba @alpzaf api metot isimleri anlamsal olarak birbirine karışıyor, bu metotların isimlerini güncelleyeceğim, lütfen bekle.

**Comment by muratgozel** [comment]
@alpzaf bazı metot isimlerini güncelledim (3.0.5) şu an sorun çözülmüş olmalı.

ayrıca katkıda bulunmak istersen `getCityNames `, `getCityCodes`, `getCities`, `getPostalCodes`, `isPostalCode` bu metotların testleri halen yok. proje pr'a açık. şuradan daha detaylı bilgi bulabilirsin: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by alpzaf** [comment]
> @alpzaf bazı metot isimlerini güncelledim (3.0.5) şu an sorun çözülmüş olmalı.
> 
> ayrıca katkıda bulunmak istersen `getCityNames `, `getCityCodes`, `getCities`, `getPostalCodes`, `isPostalCode` bu metotların testleri halen yok. proje pr'a açık. şuradan daha detaylı bilgi bulabilirsin: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Teşekkür ederim. Pr açıldıysa tabiki katkıda bulunmak isterim.
